### ISSUE TITLE
Figma Gramformer Plugin

### ISSUE THREAD

**Issue by ayoolafelix** [PrithivirajDamodaran/Gramformer#1]
Figma is used in creating a lot of digital interfaces today, a Gramformer Figma plugin would go a long way. I'll be willing to design the interface for the plugin but I don't know how to make the plugin itself. I hope someone takes this up. This is a link to get started https://www.figma.com/plugin-docs/setup/

**Comment by PrithivirajDamodaran** [comment]
Thank you but this isn't an issue. Please make it as a feature request. That way collaborators can pick it up.

**Comment by ayoolafelix** [comment]
Apologies, made a mistake.
