### ISSUE TITLE
pip install is erroring out, 

### ISSUE THREAD

**Issue by ranjan-sumit** [PrithivirajDamodaran/Gramformer#2]
I am unable to do pip install of the package, here is the error:

Collecting git+https://github.com/PrithivirajDamodaran/Gramformer.git@v0.1
  Cloning https://github.com/PrithivirajDamodaran/Gramformer.git (to revision v0.1) to c:\users\sumit\appdata\local\temp\pip-req-build-sw54k_0h
  ERROR: Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/PrithivirajDamodaran/Gramformer.git 'C:\Users\Sumit\AppData\Local\Temp\pip-req-build-sw54k_0h'
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

I also tried directly downloading the repo and tried executing the package. Model is not present in location(correction_model_tag = "prithivida/grammar_error_correcter"). Any way to download the pretrain model.

**Comment by PrithivirajDamodaran** [comment]
We don't deal with windows machines. So I recommend you try using WSL for windows and install it. It should work. 

As for as models not visible you are behind a firewall and huggingface exposes models via SSL.
