### ISSUE TITLE
Module not found Error

### ISSUE THREAD

**Issue by wafafatima66** [PrithivirajDamodaran/Gramformer#23]
I am facing this issue. It will be a great pleasure if you tell me where I am doing wrong here. 

![image](https://user-images.githubusercontent.com/44090636/154233715-8f9d6f0c-7fce-4775-9f96-6a9d8738869d.png)
![image](https://user-images.githubusercontent.com/44090636/154233996-4907a0e4-7a14-4963-92bb-21a3008049bd.png)

**Comment by PrithivirajDamodaran** [comment]
Try now with the new installation command.
