### ISSUE TITLE
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

### ISSUE THREAD

**Issue by vky2998** [PrithivirajDamodaran/Gramformer#31]
OSError                                   Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_9376\2706950954.py in <module>
     25 
     26 
---> 27 gf = Gramformer(models = 1, use_gpu=False) # 1=corrector, 2=detector
     28 
     29 influent_sentences = [

~\anaconda3_9\envs\python37\lib\site-packages\gramformer\gramformer.py in __init__(self, models, use_gpu)
      7     import errant
      8     #self.annotator = errant.load('en_core_web_sm')
----> 9     self.annotator = errant.load('en')  # en is deprecated from spacy 3.0 onwards
     10 
     11     if use_gpu:

~\anaconda3_9\envs\python37\lib\site-packages\errant\__init__.py in load(lang, nlp)
     17 
     18     # Load spacy
---> 19     nlp = nlp or spacy.load(lang, disable=["ner"])
     20 
     21     # Load language edit merger

~\anaconda3_9\envs\python37\lib\site-packages\spacy\__init__.py in load(name, **overrides)
     28     if depr_path not in (True, False, None):
     29         warnings.warn(Warnings.W001.format(path=depr_path), DeprecationWarning)
---> 30     return util.load_model(name, **overrides)
     31 
     32 

~\anaconda3_9\envs\python37\lib\site-packages\spacy\util.py in load_model(name, **overrides)
    173     elif hasattr(name, "exists"):  # Path or Path-like to model data
    174         return load_model_from_path(name, **overrides)
--> 175     raise IOError(Errors.E050.format(name=name))
    176 
    177 

OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

**Comment by MT010104** [comment]
Hi. I met the same problem. Have you solved it?

**Comment by MrShininnnnn** [comment]
This can be solved by `pip install spacy` and `python -m spacy download en`.

**Comment by kumarroshan10** [comment]
Thanku @MrShininnnnn . it worked

**Comment by Noah-Haf** [comment]
I had this issue too. 


> This can be solved by pip install spacy and python -m spacy download en.

Solved the issue.
