### ISSUE TITLE
Use corrector for highligher 

### ISSUE THREAD

**Issue by ilhamsyahids** [PrithivirajDamodaran/Gramformer#6]
Hi @PrithivirajDamodaran 

This is a great framework. Is it possible (for now) to use model corrector (model=2) for the highlighter(model=1)?
After getting some correction, match it to the input and give prefix and suffix (<e>) for the mismatch?

Thanks

**Comment by PrithivirajDamodaran** [comment]
No, highlighter is trained on a different style of data, to highlight the errors in the source sentence without correcting it. Have a look at the readme, I have shown sample outputs. So you can't use them interchangeably. 

But I would request you to wait and watch this space within a week you should get the highlighter model ready. Hang tight 😀

**Comment by ilhamsyahids** [comment]
Sounds great!
